package eweather.db;
// Generated Mar 14, 2018 10:51:13 PM by Hibernate Tools 4.3.1



/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private long id;
     private String name;

    public City() {
    }

	
    public City(long id) {
        this.id = id;
    }
    public City(long id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


