package eweather.db;
// Generated Mar 14, 2018 10:51:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Weatherdata generated by hbm2java
 */
public class Weatherdata  implements java.io.Serializable {


     private long id;
     private long cityid;
     private Date dt;
     private Float temp;
     private String description;
     private Float clouds;
     private Float windspeed;
     private Float rain;
     private Float snow;

    public Weatherdata() {
    }

	
    public Weatherdata(long id, long cityid) {
        this.id = id;
        this.cityid = cityid;
    }
    public Weatherdata(long id, long cityid, Date dt, Float temp, String description, Float clouds, Float windspeed, Float rain, Float snow) {
       this.id = id;
       this.cityid = cityid;
       this.dt = dt;
       this.temp = temp;
       this.description = description;
       this.clouds = clouds;
       this.windspeed = windspeed;
       this.rain = rain;
       this.snow = snow;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getCityid() {
        return this.cityid;
    }
    
    public void setCityid(long cityid) {
        this.cityid = cityid;
    }
    public Date getDt() {
        return this.dt;
    }
    
    public void setDt(Date dt) {
        this.dt = dt;
    }
    public Float getTemp() {
        return this.temp;
    }
    
    public void setTemp(Float temp) {
        this.temp = temp;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Float getClouds() {
        return this.clouds;
    }
    
    public void setClouds(Float clouds) {
        this.clouds = clouds;
    }
    public Float getWindspeed() {
        return this.windspeed;
    }
    
    public void setWindspeed(Float windspeed) {
        this.windspeed = windspeed;
    }
    public Float getRain() {
        return this.rain;
    }
    
    public void setRain(Float rain) {
        this.rain = rain;
    }
    public Float getSnow() {
        return this.snow;
    }
    
    public void setSnow(Float snow) {
        this.snow = snow;
    }




}


