/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eweather.gui;

import eweather.controllers.DataController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.SplashScreen;
import java.awt.geom.Rectangle2D;
import java.util.logging.Level;
import javax.swing.JFrame;

/**
 *
 * @author Trifon
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTN1 = new javax.swing.JButton();
        jBTN2 = new javax.swing.JButton();
        jBTN3 = new javax.swing.JButton();
        jBTN4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 440));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setPreferredSize(new java.awt.Dimension(640, 440));
        getContentPane().setLayout(null);

        jBTN1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBTN1.setText("Ο Καιρός Τώρα");
        jBTN1.setMaximumSize(new java.awt.Dimension(300, 50));
        jBTN1.setMinimumSize(new java.awt.Dimension(300, 50));
        jBTN1.setPreferredSize(new java.awt.Dimension(300, 50));
        jBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN1);
        jBTN1.setBounds(180, 80, 280, 40);

        jBTN2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBTN2.setText("Πρόβλεψη Καιρού");
        jBTN2.setMaximumSize(new java.awt.Dimension(300, 50));
        jBTN2.setMinimumSize(new java.awt.Dimension(300, 50));
        jBTN2.setPreferredSize(new java.awt.Dimension(300, 50));
        jBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN2);
        jBTN2.setBounds(180, 150, 280, 40);

        jBTN3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBTN3.setText("Έξοδος");
        jBTN3.setMaximumSize(new java.awt.Dimension(300, 50));
        jBTN3.setMinimumSize(new java.awt.Dimension(300, 50));
        jBTN3.setPreferredSize(new java.awt.Dimension(300, 50));
        jBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN3);
        jBTN3.setBounds(180, 290, 280, 40);

        jBTN4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBTN4.setText("Στατιστικά");
        jBTN4.setMaximumSize(new java.awt.Dimension(300, 50));
        jBTN4.setMinimumSize(new java.awt.Dimension(300, 50));
        jBTN4.setPreferredSize(new java.awt.Dimension(300, 50));
        jBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN4);
        jBTN4.setBounds(180, 220, 280, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/w.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN1ActionPerformed
        this.setVisible(false);
        FormShowCurrent f = new FormShowCurrent(this, true);
        f.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jBTN1ActionPerformed

    private void jBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN3ActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jBTN3ActionPerformed

    private void jBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN2ActionPerformed
        this.setVisible(false);
        FormShowPrognosis f = new FormShowPrognosis(this, true);
        f.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jBTN2ActionPerformed

    private void jBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN4ActionPerformed
        this.setVisible(false);
        FormStatistics f = new FormStatistics(this, true);
        f.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jBTN4ActionPerformed

    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {

        java.util.logging.Logger.getLogger("org.hibernate").setLevel(Level.SEVERE);

        splashInit();

        DataController.initCities();
        DataController.updateCurrentWeather();
        DataController.updatePrognosisWeather();


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("SystemLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMenu f = new FormMenu();
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setVisible(true);
            }
        });
    }
    
    private static SplashScreen mySplash;
    private static Rectangle2D splashTextArea;
    private static Rectangle2D splashProgressArea;
    private static Graphics splashGraphics;
    private static Font font;
    
    

    public static void splashText(String str) {
        if (mySplash != null && mySplash.isVisible()) {   
         
            splashGraphics.setColor(Color.LIGHT_GRAY);
            
            splashGraphics.setColor(Color.WHITE);
            splashGraphics.drawString(str, (int) (splashTextArea.getX() + 150), (int) (splashTextArea.getY() + 40));
           
            mySplash.update();
        }
    }

    private static void splashInit() {
        mySplash = SplashScreen.getSplashScreen();
        if (mySplash != null) {  
            Dimension ssDim = mySplash.getSize();
            int height = ssDim.height;
            int width = ssDim.width;
 
            splashTextArea = new Rectangle2D.Double(15., height * 0.88, width * .45, 32.);
            splashProgressArea = new Rectangle2D.Double(width * .55, height * .92, width * .4, 12);
           
            splashGraphics = mySplash.createGraphics();
            font = new Font("Dialog", Font.PLAIN, 14);
            splashGraphics.setFont(font);
           
            splashText("Παρακαλώ περιμένετε μέχρι να ολοκληρωθεί η ενημέρωση των στοιχείων");           
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTN1;
    private javax.swing.JButton jBTN2;
    private javax.swing.JButton jBTN3;
    private javax.swing.JButton jBTN4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
