/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eweather.gui;

import eweather.controllers.DataController;
import eweather.db.City;
import eweather.db.Weatherdata;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Trifon
 */
public class FormShowPrognosis extends javax.swing.JDialog {

    /**
     * Creates new form FormCurrent
     *
     * @param parent
     * @param modal
     */
    public FormShowPrognosis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        cityList = DataController.getCities();
        initCombo();
        initTable();
        clearTable();
    }

    List<City> cityList;

    private void initTable() {
        this.jTablePrognosis.getTableHeader().
                setPreferredSize(new Dimension(100, 40));
        this.jTablePrognosis.setIntercellSpacing(new Dimension(20, 0));
        this.jTablePrognosis.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void clearTable() {
        List<Weatherdata> t = new ArrayList<>();
        WeatherTableModel wtm = new WeatherTableModel(t);
        jTablePrognosis.setModel(wtm);
    }

    private void initCombo() {

        class ItemChangeListener implements ItemListener {

            @Override
            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    clearTable();
                }
            }
        }
        jComboCities.addItemListener(new ItemChangeListener());

        for (int i = 0; i < cityList.size(); i++) {
            this.jComboCities.addItem(cityList.get(i).getCityname());
        }
    }

    private void showPrognosis(List<Weatherdata> weatherdata) {
        WeatherTableModel model = new WeatherTableModel(weatherdata);

        this.jTablePrognosis.setModel(model);
        DefaultTableCellRenderer rr = new DefaultTableCellRenderer();
        rr.setHorizontalAlignment(JLabel.RIGHT);
        this.jTablePrognosis.getColumnModel().getColumn(4).setCellRenderer(rr);
        this.jTablePrognosis.getColumnModel().getColumn(5).setCellRenderer(rr);
        this.jTablePrognosis.getColumnModel().getColumn(6).setCellRenderer(rr);
        this.jTablePrognosis.getColumnModel().getColumn(7).setCellRenderer(rr);
        this.jTablePrognosis.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        TableColumnAdjuster tca = new TableColumnAdjuster(this.jTablePrognosis);
        tca.setColumnDataIncluded(true);
        tca.adjustColumns();
    }

    private Long getSelectedCityId() {

        int selIdx = this.jComboCities.getSelectedIndex() - 1;

        if (selIdx < 0 || selIdx >= cityList.size()) {
            JOptionPane.showMessageDialog(this,
                    "Δεν έχετε επιλέξει πόλη",
                    "Προειδοποίηση",
                    JOptionPane.WARNING_MESSAGE);
            return -1L;
        }
        return cityList.get(selIdx).getId();
    }

    private void showPrognosis1Day() {

        Long cityId = getSelectedCityId();
        if (cityId < 0) {
            return;
        }

        Date dt_start = new Date();
        List<Weatherdata> weatherdata
                = DataController.getPrognosis1Day(cityId, dt_start);

        showPrognosis(weatherdata);
    }

    private void showPrognosis5Days() {

        Long cityId = getSelectedCityId();
        if (cityId < 0) {
            return;
        }

        Date dt_start = new Date();
        List<Weatherdata> weatherdata
                = DataController.getPrognosis5Day(cityId, dt_start);

        showPrognosis(weatherdata);
    }

    private void updatePrognosis() {
        DataController.updatePrognosisWeather();
        showPrognosis1Day();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrognosis = new javax.swing.JTable();
        jBTN1 = new javax.swing.JButton();
        jBTN2 = new javax.swing.JButton();
        jBTN3 = new javax.swing.JButton();
        jComboCities = new javax.swing.JComboBox<>();
        jBTN4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ο Καιρός Τώρα");

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTablePrognosis.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTablePrognosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePrognosis.setRowHeight(55);
        jScrollPane1.setViewportView(jTablePrognosis);

        jBTN1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTN1.setText("Πρόβλεψη καιρού 1ας ημέρας");
        jBTN1.setToolTipText("Προβολή από την βάση δεδομένων των προβλέψεων 1ας ημέρας");
        jBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN1ActionPerformed(evt);
            }
        });

        jBTN2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTN2.setText("Πρόβλεψη καιρού 5 ημερών.");
        jBTN2.setToolTipText("Πρόβλεψη καιρού 5 ημερών.");
        jBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN2ActionPerformed(evt);
            }
        });

        jBTN3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTN3.setText("Επιστροφή");
        jBTN3.setToolTipText("Επιστοφή στις επιλογές της κύριας φόρμας.");
        jBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN3ActionPerformed(evt);
            }
        });

        jComboCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλέξτε μια πόλη ..." }));

        jBTN4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTN4.setText("Ανανέωση πρόβλεψης καιρού");
        jBTN4.setToolTipText("Πρόβλεψη καιρού 5 ημερών.");
        jBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBTN2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTN1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboCities, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTN4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jBTN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTN2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTN4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTN3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN1ActionPerformed
        showPrognosis1Day();
    }//GEN-LAST:event_jBTN1ActionPerformed

    private void jBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN2ActionPerformed
        showPrognosis5Days();
    }//GEN-LAST:event_jBTN2ActionPerformed

    private void jBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN3ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBTN3ActionPerformed

    private void jBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN4ActionPerformed
        updatePrognosis();
    }//GEN-LAST:event_jBTN4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTN1;
    private javax.swing.JButton jBTN2;
    private javax.swing.JButton jBTN3;
    private javax.swing.JButton jBTN4;
    private javax.swing.JComboBox<String> jComboCities;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrognosis;
    // End of variables declaration//GEN-END:variables
}
